import type {
  Agent,
  AuditEvent,
  Capability,
  ChannelContract,
  EvidenceRun,
  InstanceAssignment,
  ProviderContract,
  RoutePolicy,
  SystemMetric,
  Tenant,
  TenantAccessProfile,
  TenantEntitlement,
  TraceEvent,
  WorkspaceAssignment,
} from './types'

const now = '2026-05-29T09:30:00Z'

export const sampleTenants: Tenant[] = [
  {
    id: 'default',
    level: 0,
    name: 'Default Tenant',
    status: 'active',
    createdAt: '2026-05-20T01:00:00Z',
    updatedAt: now,
  },
  {
    id: 'default-bu',
    parentTenantId: 'default',
    level: 1,
    name: 'Default Business Unit',
    status: 'active',
    createdAt: '2026-05-20T01:10:00Z',
    updatedAt: now,
  },
  {
    id: 'default-bu-team',
    parentTenantId: 'default-bu',
    level: 2,
    name: 'Default Workspace Team',
    status: 'active',
    createdAt: '2026-05-20T01:20:00Z',
    updatedAt: now,
  },
]

export const sampleProviders: ProviderContract[] = [
  {
    schemaVersion: 'agent-provider-contract-v1',
    key: 'dify',
    label: 'Dify',
    channelType: 'a2a',
    defaultEndpoint: 'https://api.example.com/dify/a2a',
    channelConfigFields: [
      { key: 'provider', type: 'string', required: true },
      { key: 'endpoint', type: 'url', required: true, outboundUrl: true },
      { key: 'metadata', type: 'object', required: false },
    ],
    requiredCreds: ['apiBase', 'apiKey'],
    optionalCreds: ['userId'],
    futureMetadataPolicy: 'metadata object only',
  },
  {
    schemaVersion: 'agent-provider-contract-v1',
    key: 'webhook',
    label: 'Webhook',
    channelType: 'webhook',
    defaultEndpoint: 'https://api.example.com/webhook',
    channelConfigFields: [
      { key: 'provider', type: 'string', required: true },
      { key: 'endpoint', type: 'url', required: false, outboundUrl: true },
      { key: 'metadata', type: 'object', required: false },
    ],
    futureMetadataPolicy: 'metadata object only',
  },
]

export const sampleChannels: ChannelContract[] = [
  {
    schemaVersion: 'agent-channel-contract-v1',
    key: 'local',
    label: 'Local Caller',
    endpointRequiredWhenActive: false,
    channelConfigFields: [
      { key: 'description', type: 'string', required: false },
      { key: 'metadata', type: 'object', required: false },
    ],
    futureMetadataPolicy: 'metadata object only',
  },
  {
    schemaVersion: 'agent-channel-contract-v1',
    key: 'mcp',
    label: 'MCP Server',
    endpointRequiredWhenActive: true,
    channelConfigFields: [
      { key: 'endpoint', type: 'url', required: true, outboundUrl: true },
      { key: 'transport', type: 'string', required: false },
      { key: 'headers', type: 'object', required: false, secretDisallowed: true },
      { key: 'credentialHeaders', type: 'object', required: false },
      { key: 'timeoutMs', type: 'integer', required: false },
      { key: 'retry', type: 'object', required: false },
      { key: 'metadata', type: 'object', required: false },
    ],
    futureMetadataPolicy: 'metadata object only',
  },
  {
    schemaVersion: 'agent-channel-contract-v1',
    key: 'openapi',
    label: 'OpenAPI Service',
    endpointRequiredWhenActive: true,
    channelConfigFields: [
      { key: 'endpoint', type: 'url', required: true, outboundUrl: true },
      { key: 'specUrl', type: 'url', required: false, outboundUrl: true },
      { key: 'headers', type: 'object', required: false, secretDisallowed: true },
      { key: 'credentialHeaders', type: 'object', required: false },
      { key: 'timeoutMs', type: 'integer', required: false },
      { key: 'retry', type: 'object', required: false },
      { key: 'metadata', type: 'object', required: false },
    ],
    futureMetadataPolicy: 'metadata object only',
  },
  {
    schemaVersion: 'agent-channel-contract-v1',
    key: 'a2a',
    label: 'A2A Agent',
    endpointRequiredWhenActive: true,
    channelConfigFields: [
      { key: 'endpoint', type: 'url', required: true, outboundUrl: true },
      { key: 'provider', type: 'string', required: false },
      { key: 'headers', type: 'object', required: false, secretDisallowed: true },
      { key: 'credentialHeaders', type: 'object', required: false },
      { key: 'timeoutMs', type: 'integer', required: false },
      { key: 'retry', type: 'object', required: false },
      { key: 'metadata', type: 'object', required: false },
    ],
    futureMetadataPolicy: 'metadata object only',
  },
  {
    schemaVersion: 'agent-channel-contract-v1',
    key: 'webhook',
    label: 'Webhook',
    endpointRequiredWhenActive: false,
    channelConfigFields: [
      { key: 'endpoint', type: 'url', required: false, outboundUrl: true },
      { key: 'metadata', type: 'object', required: false },
    ],
    futureMetadataPolicy: 'metadata object only',
  },
]

export const sampleAgents: Agent[] = [
  {
    id: 'agt_console_ops',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    name: 'Operations Console Caller',
    description: 'Internal caller used by console workflows and operational playbooks.',
    ownerId: 'platform-team',
    channelType: 'local',
    channelConfig: { description: 'Browser initiated control-plane calls' },
    credentialVersion: 0,
    status: 'active',
    createdAt: '2026-05-20T02:10:00Z',
    updatedAt: now,
  },
  {
    id: 'agt_policy_router',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    name: 'Policy Router',
    description: 'Routes approved requests to downstream business automation agents.',
    ownerId: 'automation-team',
    channelType: 'mcp',
    channelConfig: {
      endpoint: 'https://api.example.com/mcp/policy-router',
      transport: 'streamable-http',
      metadata: { tier: 'standard' },
    },
    credentialVersion: 3,
    status: 'active',
    createdAt: '2026-05-21T04:00:00Z',
    updatedAt: '2026-05-28T13:12:00Z',
  },
  {
    id: 'agt_knowledge_gateway',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    name: 'Knowledge Gateway',
    description: 'Read-only gateway for enterprise knowledge retrieval.',
    ownerId: 'knowledge-team',
    channelType: 'openapi',
    channelConfig: {
      endpoint: 'https://api.example.com/knowledge',
      specUrl: 'https://api.example.com/knowledge/openapi.json',
      metadata: { sensitivity: 'internal' },
    },
    credentialVersion: 2,
    status: 'active',
    createdAt: '2026-05-22T08:30:00Z',
    updatedAt: '2026-05-28T15:45:00Z',
  },
  {
    id: 'agt_review_webhook',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    name: 'Review Webhook',
    description: 'Receives asynchronous review notifications from approved services.',
    ownerId: 'integration-team',
    channelType: 'webhook',
    channelConfig: {
      endpoint: 'https://api.example.com/webhook/review',
      metadata: { retryPolicy: 'bounded' },
    },
    credentialVersion: 0,
    status: 'draft',
    createdAt: '2026-05-25T11:20:00Z',
    updatedAt: '2026-05-27T10:05:00Z',
  },
]

export const sampleCapabilities: Capability[] = [
  {
    id: 'cap_search_customer',
    targetId: 'agt_policy_router',
    type: 'mcp_tool',
    key: 'search_customer',
    displayName: 'search_customer',
    description: 'Search customer records by account, owner, or lifecycle stage.',
    action: 'read',
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object' },
    dataDomains: ['crm'],
    dataScopes: [
      {
        dataDomain: 'crm',
        dataset: 'customers',
        classification: 'internal',
        tenantFilter: 'tenantId = default',
      },
    ],
    sensitivity: 'internal',
    riskLevel: 'low',
    enforcementMode: 'gateway',
    discoveryStatus: 'approved',
    version: 1,
    discoveredAt: '2026-05-29T08:40:00Z',
    updatedAt: '2026-05-29T08:42:00Z',
  },
  {
    id: 'cap_export_contracts',
    targetId: 'agt_policy_router',
    type: 'mcp_tool',
    key: 'export_contracts',
    displayName: 'export_contracts',
    description: 'Export contract packages and attached commercial terms.',
    action: 'export',
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object' },
    dataDomains: ['contracts'],
    dataScopes: [
      {
        dataDomain: 'contracts',
        dataset: 'contract_packages',
        classification: 'confidential',
        maskingPolicy: 'redact-commercial-terms',
      },
    ],
    sensitivity: 'confidential',
    riskLevel: 'high',
    enforcementMode: 'gateway',
    discoveryStatus: 'pending_review',
    version: 1,
    discoveredAt: '2026-05-29T08:40:00Z',
    updatedAt: '2026-05-29T08:40:00Z',
  },
]

export const sampleTenantEntitlements: TenantEntitlement[] = [
  {
    id: 'ent_search_customer',
    tenantId: 'default',
    targetId: 'agt_policy_router',
    capabilityId: 'cap_search_customer',
    effect: 'allow',
    dataScopes: sampleCapabilities[0].dataScopes,
    status: 'enabled',
    priority: 50,
    createdAt: '2026-05-29T08:43:00Z',
    updatedAt: '2026-05-29T08:43:00Z',
  },
]

export const sampleWorkspaceAssignments: WorkspaceAssignment[] = [
  {
    id: 'wsa_search_customer',
    tenantEntitlementId: 'ent_search_customer',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    effect: 'allow',
    dataScopes: sampleCapabilities[0].dataScopes,
    status: 'enabled',
    createdAt: '2026-05-29T08:44:00Z',
    updatedAt: '2026-05-29T08:44:00Z',
  },
]

export const sampleInstanceAssignments: InstanceAssignment[] = [
  {
    id: 'ina_search_customer',
    workspaceAssignmentId: 'wsa_search_customer',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    callerInstanceId: 'agt_console_ops',
    subjectSelector: 'user:*',
    effect: 'allow',
    dataScopes: sampleCapabilities[0].dataScopes,
    status: 'enabled',
    createdAt: '2026-05-29T08:45:00Z',
    updatedAt: '2026-05-29T08:45:00Z',
  },
]

export const sampleTraces: TraceEvent[] = [
  {
    id: 'trc_1001',
    runId: 'run_20260529_001',
    callerAgentId: 'agt_console_ops',
    targetAgentId: 'agt_policy_router',
    routeType: 'mcp',
    routeKey: 'tools/call',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    callerInstanceId: 'agt_console_ops',
    subjectId: 'user:ops-console',
    capabilityId: 'cap_search_customer',
    capabilityVersion: 1,
    entitlementId: 'ent_search_customer',
    workspaceAssignmentId: 'wsa_search_customer',
    instanceAssignmentId: 'ina_search_customer',
    dataScopes: sampleCapabilities[0].dataScopes,
    decision: 'allowed',
    reason: 'capability grant chain matched',
    createdAt: '2026-05-29T08:45:11Z',
  },
  {
    id: 'trc_1002',
    runId: 'run_20260529_002',
    callerAgentId: 'agt_console_ops',
    targetAgentId: 'agt_knowledge_gateway',
    routeType: 'openapi',
    routeKey: 'search',
    decision: 'allowed',
    reason: 'access grant matched',
    createdAt: '2026-05-29T08:51:27Z',
  },
  {
    id: 'trc_1003',
    runId: 'run_20260529_003',
    callerAgentId: 'agt_review_webhook',
    targetAgentId: 'agt_knowledge_gateway',
    routeType: 'openapi',
    routeKey: 'admin/export',
    decision: 'denied',
    reason: 'caller has no access grant for target route',
    createdAt: '2026-05-29T09:02:44Z',
  },
]

export const sampleTenantAccessProfile: TenantAccessProfile = {
  tenant: sampleTenants[0],
  scopeTenants: sampleTenants,
  summary: {
    tenantCount: sampleTenants.length,
    grantCount: 1,
    targetCount: 1,
    capabilityCount: 1,
    workspaceAssignmentCount: 1,
    instanceAssignmentCount: 1,
    recentAllowedTraceCount: 1,
    recentDeniedTraceCount: 0,
  },
  grants: [
    {
      tenantEntitlement: sampleTenantEntitlements[0],
      target: sampleAgents[1],
      capability: sampleCapabilities[0],
      effectiveTenantDataScopes: sampleCapabilities[0].dataScopes,
      scopeStatus: 'valid',
      workspaceAssignments: [
        {
          workspaceAssignment: sampleWorkspaceAssignments[0],
          effectiveWorkspaceDataScopes: sampleWorkspaceAssignments[0].dataScopes,
          scopeStatus: 'valid',
          instanceAssignments: [
            {
              instanceAssignment: sampleInstanceAssignments[0],
              callerInstance: sampleAgents[0],
              effectiveInstanceDataScopes: sampleInstanceAssignments[0].dataScopes,
              scopeStatus: 'valid',
            },
          ],
        },
      ],
    },
  ],
  recentTraces: [sampleTraces[0]],
  generatedAt: now,
}

export const sampleAuditEvents: AuditEvent[] = [
  {
    id: 'aud_1001',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    actor: 'platform-admin',
    action: 'agent.created',
    resourceType: 'agent',
    resourceId: 'agt_review_webhook',
    summary: 'Review Webhook was registered as a draft webhook agent.',
    metadata: { credentialVersion: 0, channelType: 'webhook' },
    createdAt: '2026-05-25T11:20:00Z',
  },
  {
    id: 'aud_1002',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    actor: 'ops-console',
    action: 'agent.credentials_rotated',
    resourceType: 'agent',
    resourceId: 'agt_policy_router',
    summary: 'Policy Router credentials were rotated from the management console.',
    metadata: { credentialVersion: 3, credentialKeys: ['apiToken'] },
    createdAt: '2026-05-28T13:12:00Z',
  },
  {
    id: 'aud_1003',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    actor: 'platform-admin',
    action: 'access_grant.created',
    resourceType: 'access_grant',
    resourceId: 'pol_002',
    summary: 'Console knowledge search route grant was created.',
    metadata: { routeType: 'openapi', routeKey: 'search' },
    createdAt: '2026-05-29T08:50:15Z',
  },
]

export const routePolicies: RoutePolicy[] = [
  {
    id: 'pol_001',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    name: 'Console to policy router',
    callerAgentId: 'agt_console_ops',
    targetAgentId: 'agt_policy_router',
    routeType: 'mcp',
    routeKey: 'tools/call',
    effect: 'allow',
    status: 'enabled',
    priority: 10,
    retry: { maxAttempts: 2, backoffMs: 25, statusCodes: [502, 503, 504] },
    lastMatchedAt: '2026-05-29T08:45:11Z',
    createdAt: '2026-05-20T03:00:00Z',
    updatedAt: '2026-05-20T03:00:00Z',
  },
  {
    id: 'pol_002',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    name: 'Console knowledge search',
    callerAgentId: 'agt_console_ops',
    targetAgentId: 'agt_knowledge_gateway',
    routeType: 'openapi',
    routeKey: 'search',
    effect: 'allow',
    status: 'enabled',
    priority: 20,
    lastMatchedAt: '2026-05-29T08:51:27Z',
    createdAt: '2026-05-22T09:00:00Z',
    updatedAt: '2026-05-22T09:00:00Z',
  },
  {
    id: 'pol_003',
    tenantId: 'default',
    workspaceId: 'workspace-sandbox',
    name: 'Webhook export safeguard',
    callerAgentId: 'agt_review_webhook',
    targetAgentId: 'agt_knowledge_gateway',
    routeType: 'openapi',
    routeKey: 'admin/export',
    effect: 'deny',
    status: 'enabled',
    priority: 5,
    lastMatchedAt: '2026-05-29T09:02:44Z',
    createdAt: '2026-05-25T12:00:00Z',
    updatedAt: '2026-05-25T12:00:00Z',
  },
]

export const evidenceRuns: EvidenceRun[] = [
  {
    id: 'evd_001',
    runId: 'run_20260529_001',
    title: 'MCP route authorization check',
    agentId: 'agt_policy_router',
    decision: 'allowed',
    status: 'passed',
    checks: 8,
    startedAt: '2026-05-29T08:45:08Z',
    completedAt: '2026-05-29T08:45:12Z',
    summary: 'Route, caller identity, and policy scope matched expected controls.',
  },
  {
    id: 'evd_002',
    runId: 'run_20260529_002',
    title: 'Knowledge gateway request review',
    agentId: 'agt_knowledge_gateway',
    decision: 'allowed',
    status: 'passed',
    checks: 6,
    startedAt: '2026-05-29T08:51:22Z',
    completedAt: '2026-05-29T08:51:28Z',
    summary: 'OpenAPI route used an approved read-only operation.',
  },
  {
    id: 'evd_003',
    runId: 'run_20260529_003',
    title: 'Privileged export guardrail',
    agentId: 'agt_knowledge_gateway',
    decision: 'denied',
    status: 'warning',
    checks: 7,
    startedAt: '2026-05-29T09:02:40Z',
    completedAt: '2026-05-29T09:02:45Z',
    summary: 'Request was blocked because the caller has no grant for the export route.',
  },
]

export const systemMetrics: SystemMetric[] = [
  {
    id: 'gateway_calls_total',
    label: 'Gateway calls',
    value: 128,
    trend: 'flat',
    status: 'healthy',
    updatedAt: now,
  },
  {
    id: 'allowed_rate',
    label: 'Allowed rate',
    value: 96,
    unit: '%',
    trend: 'flat',
    status: 'healthy',
    updatedAt: now,
  },
  {
    id: 'upstream_error_rate',
    label: 'Upstream errors',
    value: 2,
    unit: '%',
    trend: 'flat',
    status: 'warning',
    updatedAt: now,
  },
  {
    id: 'avg_latency_ms',
    label: 'Avg latency',
    value: 42,
    unit: 'ms',
    trend: 'flat',
    status: 'healthy',
    updatedAt: now,
  },
]
